import { useEffect, useRef, useState, type FormEvent, type RefObject, type ReactNode } from "react";
import { assess } from "./engine";
import { SAMPLE_MESSAGE } from "./sources";
import type { IncidentState, IntakeMode } from "./types";

type View = "intake" | "working" | "record";
type IntakeRecord = Pick<IncidentState, "thread_id" | "raw_evidence_refs" | "events_and_timeline" | "facts_shared" | "incident_type" | "uncertainty_notes" | "redaction_notice">;
const WORK_STEPS = ["Secure the evidence", "Extract observed facts", "Create incident record"];

export default function App() {
  const [view, setView] = useState<View>("intake"); const [mode, setMode] = useState<IntakeMode>("message"); const [text, setText] = useState(""); const [fileName, setFileName] = useState<string>(); const [previewUrl, setPreviewUrl] = useState<string>(); const [record, setRecord] = useState<IntakeRecord | null>(null); const [error, setError] = useState<string | null>(null); const [adding, setAdding] = useState(false); const [tick, setTick] = useState(0); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  useEffect(() => { if (view !== "working") return; setTick(0); const timers = [0, 1, 2].map((i) => window.setTimeout(() => setTick(i + 1), 300 + i * 300)); const done = window.setTimeout(() => { setView("record"); setAdding(false); }, 1250); return () => { timers.forEach(clearTimeout); clearTimeout(done); }; }, [view]);
  function clearFields() { setText(""); setFileName(undefined); if (previewUrl) URL.revokeObjectURL(previewUrl); setPreviewUrl(undefined); if (fileRef.current) fileRef.current.value = ""; }
  function submit(event: FormEvent) { event.preventDefault(); if (!text.trim() && !fileName) { setError("Add a message, description, or screenshot before creating a record."); return; } const next = assess({ text, mode, fileName, prior: adding ? record as IncidentState : undefined }); setRecord({ thread_id: next.thread_id, raw_evidence_refs: next.raw_evidence_refs, events_and_timeline: next.events_and_timeline, facts_shared: next.facts_shared, incident_type: next.incident_type, uncertainty_notes: next.uncertainty_notes, redaction_notice: next.redaction_notice }); setError(null); clearFields(); setView("working"); }
  function chooseFile(file?: File) { if (previewUrl) URL.revokeObjectURL(previewUrl); if (!file) { setFileName(undefined); setPreviewUrl(undefined); return; } setFileName(file.name); setPreviewUrl(URL.createObjectURL(file)); setMode("screenshot"); }
  function startOver() { clearFields(); setRecord(null); setAdding(false); setError(null); setView("intake"); }
  return <div className="app"><header className="top"><div className="brand"><span className="mark" aria-hidden="true" /><div><p className="wordmark">ScamSafe</p><p className="tag">Capture the facts. Decide what comes next later.</p></div></div><p className="disclaimer">This creates an incident record only. Do not share passwords, OTPs, PINs, or full card numbers.</p></header><main>{view === "intake" && <Intake mode={mode} text={text} error={error} fileName={fileName} previewUrl={previewUrl} adding={adding} fileRef={fileRef} onMode={setMode} onText={setText} onFile={chooseFile} onSubmit={submit} onSample={() => { setMode("message"); setText(SAMPLE_MESSAGE); setError(null); }} />}{view === "working" && <Working tick={tick} />}{view === "record" && record && <RecordView record={record} onAdd={() => { setAdding(true); setError(null); setView("intake"); }} onStartOver={startOver} />}</main><footer className="foot"><span className="muted">Intake preview · local rule-based mock</span>{record && <button className="textish" type="button" onClick={startOver}>Start over</button>}</footer></div>;
}

function Intake(props: { mode: IntakeMode; text: string; error: string | null; fileName?: string; previewUrl?: string; adding: boolean; fileRef: RefObject<HTMLInputElement | null>; onMode: (mode: IntakeMode) => void; onText: (value: string) => void; onFile: (file?: File) => void; onSubmit: (event: FormEvent) => void; onSample: () => void; }) { return <section className="panel"><p className="eyebrow">{props.adding ? "Add evidence" : "Incident intake"}</p><h1>{props.adding ? "What else should we record?" : "What happened?"}</h1><p className="lede">Share a message, your description, or a screenshot. We will extract a factual incident record—no advice yet.</p><form onSubmit={props.onSubmit}><div className="tabs" role="tablist">{(["message", "describe", "screenshot"] as IntakeMode[]).map((item) => <button key={item} type="button" role="tab" aria-selected={props.mode === item} className={props.mode === item ? "tab on" : "tab"} onClick={() => props.onMode(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div><label className="sr" htmlFor="evidence">Evidence or description</label><textarea id="evidence" rows={props.mode === "describe" ? 5 : 7} value={props.text} onChange={(event) => props.onText(event.target.value)} placeholder={props.mode === "message" ? "Paste an SMS, chat, or email here." : props.mode === "describe" ? "Describe what happened and what the other person asked you to do." : "Optional: add what the screenshot shows."} />{props.mode === "screenshot" && <div className="upload"><input ref={props.fileRef} type="file" accept="image/*" onChange={(event) => props.onFile(event.target.files?.[0])} />{props.previewUrl && <img className="thumb" src={props.previewUrl} alt="Attached screenshot preview" />}</div>}<p className="helper">You can submit text, a screenshot, or both. Sensitive values are redacted before storage.</p>{props.error && <p className="error" role="alert">{props.error}</p>}<div className="row"><button type="submit" className="primary">Create incident record</button>{!props.adding && <button type="button" className="secondary" onClick={props.onSample}>Use sample</button>}</div></form></section>; }
function Working({ tick }: { tick: number }) { return <section className="panel working" aria-live="polite"><p className="eyebrow">Processing intake</p><h1>Building your incident record</h1><ol className="steps">{WORK_STEPS.map((step, index) => <li key={step} className={tick > index ? "done" : tick === index ? "now" : ""}>{step}</li>)}</ol></section>; }
function RecordView({ record, onAdd, onStartOver }: { record: IntakeRecord; onAdd: () => void; onStartOver: () => void }) { return <section className="panel"><p className="eyebrow">Record created</p><h1>Here is what we captured</h1><div className="record-id"><span>Thread ID</span><code>{record.thread_id}</code></div>{record.redaction_notice && <p className="notice">{record.redaction_notice}</p>}<RecordSection title="Incident type"><p>{record.incident_type}</p></RecordSection><RecordSection title="Facts"><ListOrEmpty items={record.facts_shared} empty="No clear facts extracted yet." /></RecordSection><RecordSection title="Timeline"><ul className="timeline">{record.events_and_timeline.map((event, index) => <li key={`${event.time_hint}-${index}`}><strong>{event.time_hint}</strong><span>{event.observation}</span></li>)}</ul></RecordSection>{record.uncertainty_notes.length > 0 && <RecordSection title="Uncertainty"><ListOrEmpty items={record.uncertainty_notes} /></RecordSection>}<RecordSection title="Evidence references"><ListOrEmpty items={record.raw_evidence_refs} /></RecordSection><div className="row"><button type="button" className="primary" onClick={onAdd}>Add more evidence</button><button type="button" className="secondary" onClick={onStartOver}>Start a new record</button></div></section>; }
function RecordSection({ title, children }: { title: string; children: ReactNode }) { return <article className="record-section"><h2>{title}</h2>{children}</article>; }
function ListOrEmpty({ items, empty }: { items: string[]; empty?: string }) { return items.length ? <ul className="facts">{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p className="muted">{empty ?? "None recorded."}</p>; }
